version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: sudo apt-get install xvfb freeglut3-dev
      - run: pip3 install --user -e .
      - run: pip3 install --user flake8
      - run: python3 -m flake8 . --count --show-source --statistics --select=E901,E999,F821,F822,F823
      - run: xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" ./run_tests.py
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
